version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.projectreactor.netty:reactor-netty
    versions:
    - 1.0.4
    - 1.0.5
    - 1.0.6
  - dependency-name: io.projectreactor:reactor-core
    versions:
    - 3.4.3
    - 3.4.4
    - 3.4.5
  - dependency-name: org.springframework.data:spring-data-r2dbc
    versions:
    - 1.2.4
    - 1.2.5
    - 1.2.6
    - 1.2.7
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.28"
    - "1.29"
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.28"
    - "1.29"
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.2
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.40"
    - "8.41"
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
    versions:
    - 3.1.2
