version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:13.0.2-jdk-buster

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Static analysis
      - run: mvn checkstyle:checkstyle

      # Unit tests
      - run: mvn test
      # - run: bash <(curl -s https://codecov.io/bash)

      - run: mvn sonar:sonar

      # Package
      - run: mvn package -DskipTests

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud